[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Przekierowanie API do funkcji Netlify
[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200
  force = true

# Zmienne środowiskowe
[build.environment]
  NETLIFY = "true"

# Ustawienia funkcji
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Funkcja zaplanowana do codziennej synchronizacji danych reklamowych
[functions."scheduled-sync"]
  schedule = "@daily"