[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Przekierowanie API do funkcji Netlify
[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200
  force = true

# Zmienne środowiskowe
[build.environment]
  NETLIFY = "true"

# Ustawienia funkcji
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

  # Zwiększamy timeout dla funkcji
  [functions.contact]
    included_files = ["node_modules/nodemailer/**"]
    timeout = 30